dist: trusty
language: nix
script:
- git clone https://github.com/holochain/holochain-rust.git
- ls
- nix-shell --run 'npm run test && npm run build' ./holochain-rust/shell.nix
- PACKAGE_NAME=$(node -p -e "require('./package.json').name")
- PACKAGE_VERSION=$(node -p -e "require('./package.json').version")
- cd dna-src
- ls
- zip -r $PACKAGE_NAME-$PACKAGE_VERSION.zip *
deploy:
  provider: releases
  api-key:
    secure: AFW9AVOsFt5DlNpAl/I4kiEoYuinbE4AfRXxGsLaMKKfPFJyw7edKFrxv/tS3gUarlJerwWjcQyE4BU4NbypWmXUqOOhnq6ScvU8xA1+c+aKgF+RLqHE/YDvCzm+cqEvya+uj5l0wxKqenvSPUmh9Js68zAtSCPKr3tHjsj8l5CToHTGnJH4GUVA78hrJqyv58/QyrmxuXy7fdAIyC8cSKyzIUHfMMpvlAJxjKhkf3T4A0JfQ0R5nx7TxrGIKsj5FkUMaC+he/C841jmoatXUD23lMVSdKGE6yV7sR49c64JN7O94S3eCwoQjnLgO81V0EMA0bqbZ5lb6t8rAYqdLfiJpVT2lzktfUQ9YZqE5Cd25LVHpHQX5molVzYDm2SnqRgN8bbTBe3ITcuetPtz13KAkm/EdO7M/ZZZi7E5c0gSQuR+WSiJr1PRyY1RN2YQyzfqRNWY5LBZwuptg+Wyb7zYzb1BxaCULJ/ByEDH78J7yHywMstPuuz5FibXoaPqwDy71Mq6nOFF3Hu5wigwmEU5CY40tlXMtQZmKrHY/G2Qcs7+28Xp1JwWdC3RhKB0w11rWhuH3DJBYLDaFAfB1q7rG/JbhRKa0/LWjVMFFciSkpgpI2O40kreYh3XCj5PVFu4Qxbam1i12HD7Ny8qfOOyzORYxDfEDiIekdPd+B4=
  file: "$PACKAGE_NAME-$PACKAGE_VERSION.zip"
  skip_cleanup: true
  on:
    tags: true
    branch: master
