dist: trusty

language: nix

script:
  - git clone https://github.com/holochain/holochain-rust.git
  - ls
  - nix-shell --run 'npm run test && npm run build' ./holochain-rust/shell.nix
  - cd dna
  - ls
