dist: trusty

language: node_js

node_js:
  - '11'

services:
- docker

script:
  - docker run -v "$(pwd):/hylo-holo-dnas" holochain/holochain-rust:latest bash -c "nix-shell --run 'hc test --dir /hylo-holo-dnas/dna-src'"
