dist: trusty

language: node_js

node_js:
  - '11'

services:
- docker

before_install:
  - wget --header='Accept:application/octet-stream' https://api.github.com/repos/holochain/holochain-rust/releases/assets/12164716 -O hc.tar.gz
  - tar xvfz hc.tar.gz
  - ls
  - hcdir=$(dirname $(find . -iname 'hc')) && cd $hcdir
  - mv hc ../
  - cd ..
  - ls
script:
  - docker run -v "$(pwd):/hylo-holo-dnas" holochain/holochain-rust:develop bash -c "cd /hylo-holo-dnas && ls"
