dist: trusty

language: node_js

node_js:
  - '11'

services:
- docker

script:
  - docker run -v "$(pwd):/hylo-holo-dnas" holochain/holochain-rust:latest bash -c "cd /hylo-holo-dnas/dna-src && ./hc test"
