version: '2'

services:

  # bootstrap:
  #   image: holochain/holochain-rust:latest
  #   ports:
  #     - "3142:3142"
  #   command: bs

  hylo1:
    image: holochain/holochain-rust:latest
    ports:
      - "4000:4000"
    depends_on:
      - bootstrap
    volumes:
      - "${TARGETDIR}:/hylo-holo-dnas"
    command: bash -c "nix-shell --run 'holochain -c /hylo-holo-dnas/conductor-config-agent1.toml'"
