# * Copy this file to conductor-config.toml and generate a unique agent key
#   for your instance of Hylo DNA:
#
#    1. Run `hc keygen -n`
#    2. Copy the public address hash and copy it into public_address below
#    3. Point the path noted in "Keystore written to:" to keystore_file below

# -- Hylo DNA, Agent and Instance config

[[dnas]]
id = "hylo_dna"
file = "./dna/hylo.dna.json"
hash = "Qm328wyq38924y"

[[agents]]
id = "hylo_agent"
name = "Holochain for Hylo agent"
public_address = ""
keystore_file = ""

[[instances]]
id = "hylo-chat"
dna = "hylo_dna"
agent = "hylo_agent"

  [instances.logger]
  type = "simple"
  file = "app_spec.log"

  [instances.storage]
  type = "memory"
  path = "tmp-storage"

# -- Hylo DNA WS-RPC interface

[[interfaces]]
id = "websocket_interface"

    [[interfaces.instances]]
    id = "hylo-chat"

    [interfaces.driver]
    type = "websocket"
    port = 3400

# -- Hylo UI Bundle (location of files) and UI Interface (http)

[[ui_bundles]]
id = "hylo-ui"
root_dir = "./hylo-ui"

[[ui_interfaces]]
bundle = "hylo-ui"
dna_interface = "websocket_interface"
id = "hylo-ui-interface"
port = 8000

# -- GraphiQl UI Bundle (location of files) and UI Interface (http)

[[ui_bundles]]
id = "graphiql-ui"
root_dir = "./graphiql-ui/build"

[[ui_interfaces]]
bundle = "graphiql-ui"
dna_interface = "websocket_interface"
id = "graphiql-ui-interface"
port = 5000

# -- Networking

[network]
n3h_persistence_path = "/tmp"
n3h_log_level = "t"
bootstrap_nodes = []
# # For testing with a persistent n3h bootstrap node
# bootstrap_nodes = [
#   "wss://holo-dna.hylo.com:38474/?a=HcSCirG9ghgy9owfdiSmaibqwD5jz9tfb5iBd4QRXrqheadsviW8bw3W3qCrm3r"
# ]

# -- Logger (settings below will disable most logging) --

# [logger]
# type="debug"
# [[logger.rules.rules]]
# exclude=true
# pattern=".*"
