# -- Hylo DNA, Agent and Instance config

[[dnas]]
id = "hylo_dna"
file = "./dna/hylo.dna.json"
hash = "Qm328wyq38924y"

[[agents]]
id = "hylo_agent"
name = "HoloTester3"
public_address = "HcScIpNoy4Q5Xw76ggYWeMRcH5yxyitijRaREZHF9P6dau76aJygYS67G8Fcydi"
keystore_file = "./keystores/agent3.keystore"

[[instances]]
id = "hylo"
dna = "hylo_dna"
agent = "hylo_agent"

  [instances.logger]
  type = "simple"
  file = "app_spec.log"

  [instances.storage]
  type = "memory"
  path = "tmp-storage"

# -- Hylo DNA WS-RPC interface

[[interfaces]]
id = "websocket_interface"

    [[interfaces.instances]]
    id = "hylo"

    [interfaces.driver]
    type = "websocket"
    port = 3403

# -- Hylo UI Bundle (location of files) and UI Interface (http)

[[ui_bundles]]
id = "hylo-ui"
root_dir = "./hylo-ui"

[[ui_interfaces]]
bundle = "hylo-ui"
dna_interface = "websocket_interface"
id = "hylo-ui-interface"
port = 8003

# -- GraphiQl UI Bundle (location of files) and UI Interface (http)

[[ui_bundles]]
id = "graphiql-ui"
root_dir = "./graphiql-ui/build"

[[ui_interfaces]]
bundle = "graphiql-ui"
dna_interface = "websocket_interface"
id = "graphiql-ui-interface"
port = 5003

# -- Networking

[network]
n3h_persistence_path = "tmp/agent3"
n3h_mode = "REAL"
n3h_log_level = "t"
bootstrap_nodes = []

# # For testing with a persistent n3h bootstrap node
# bootstrap_nodes = [
#   "wss://holo-dna.hylo.com:38474/?a=HcSCirG9ghgy9owfdiSmaibqwD5jz9tfb5iBd4QRXrqheadsviW8bw3W3qCrm3r"
# ]

# -- Logger (settings below will disable most logging) --

# [logger]
# type="debug"
# [[logger.rules.rules]]
# exclude=true
# pattern=".*"
